// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-UIRU1vaZYpys5jk_k7yxCqKIQpIet1c',
    appId: '1:307562021892:web:af8f5a84774a4fc5126151',
    messagingSenderId: '307562021892',
    projectId: 'homework-tracker-4f86d',
    authDomain: 'homework-tracker-4f86d.firebaseapp.com',
    storageBucket: 'homework-tracker-4f86d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnT4CAI1eMptOxjUuzmU79Om8XOhPdnMk',
    appId: '1:307562021892:android:2a0eb078c6148962126151',
    messagingSenderId: '307562021892',
    projectId: 'homework-tracker-4f86d',
    storageBucket: 'homework-tracker-4f86d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_TnIMzSUnS8Oklg7Mk_fiRCqW7A7wdok',
    appId: '1:307562021892:ios:958870a01d88f94b126151',
    messagingSenderId: '307562021892',
    projectId: 'homework-tracker-4f86d',
    storageBucket: 'homework-tracker-4f86d.firebasestorage.app',
    iosBundleId: 'com.example.jfkgdkhkfd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_TnIMzSUnS8Oklg7Mk_fiRCqW7A7wdok',
    appId: '1:307562021892:ios:958870a01d88f94b126151',
    messagingSenderId: '307562021892',
    projectId: 'homework-tracker-4f86d',
    storageBucket: 'homework-tracker-4f86d.firebasestorage.app',
    iosBundleId: 'com.example.jfkgdkhkfd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-UIRU1vaZYpys5jk_k7yxCqKIQpIet1c',
    appId: '1:307562021892:web:14f9f249ec893a72126151',
    messagingSenderId: '307562021892',
    projectId: 'homework-tracker-4f86d',
    authDomain: 'homework-tracker-4f86d.firebaseapp.com',
    storageBucket: 'homework-tracker-4f86d.firebasestorage.app',
  );
}
